### ISSUE TITLE
Error using Docker: thread 'rocket-worker-thread' panicked

### ISSUE THREAD

**Issue by Milamber07** [dorianim/money-balancer#16]
Hi,

I was launching money-balancer via docker-compose on Synology NAS.

And get this error when I attempt to register new user. Screenshot and container logs below.

Please advice.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/25886632/203326610-896e3477-b3e1-4169-97b5-722cd630fb32.png">

```
22/11/2022 16:22:13
   >> No 409 catcher registered. Using Rocket default.
22/11/2022 16:22:22
   >> No 409 catcher registered. Using Rocket default.
22/11/2022 16:22:59
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/guards/authentication.rs:83:12
22/11/2022 16:22:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
22/11/2022 16:22:59
   >> Handler token panicked.
22/11/2022 16:22:59
   >> A panic is treated as an internal server error.
22/11/2022 16:22:59
   >> No 500 catcher registered. Using Rocket default.
22/11/2022 16:23:11
   >> No 401 catcher registered. Using Rocket default.
22/11/2022 16:23:15
   >> No 401 catcher registered. Using Rocket default.
22/11/2022 16:23:16
   >> No 401 catcher registered. Using Rocket default.
22/11/2022 16:23:25
   >> No 401 catcher registered. Using Rocket default.
22/11/2022 16:23:27
   >> No 401 catcher registered. Using Rocket default.
22/11/2022 16:23:28
   >> No 401 catcher registered. Using Rocket default.
22/11/2022 16:23:29
   >> No 401 catcher registered. Using Rocket default.
22/11/2022 16:24:25
   >> No 409 catcher registered. Using Rocket default.
22/11/2022 16:24:37
   >> No 409 catcher registered. Using Rocket default.
22/11/2022 16:24:43
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/guards/authentication.rs:83:12
22/11/2022 16:24:43
   >> Handler token panicked.
22/11/2022 16:24:43
   >> A panic is treated as an internal server error.
22/11/2022 16:24:43
   >> No 500 catcher registered. Using Rocket default.
22/11/2022 16:24:53
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/guards/authentication.rs:83:12
22/11/2022 16:24:53
   >> Handler token panicked.
22/11/2022 16:24:53
   >> A panic is treated as an internal server error.
22/11/2022 16:24:53
   >> No 500 catcher registered. Using Rocket default.
```

**Comment by dorianim** [comment]
Did you set the JWT_TOKEN environment variable?

**Comment by Milamber07** [comment]
> Did you set the JWT_SECRET environment variable?

Yeah, I did set it to 32 character length. 

>I'm sorry, the current latest tag is not compatible with the documentation of the main branch. For the documentation of latest, see here: https://github.com/dorianim/money-balancer/tree/v1.2.0

My docker-compose looks exactly the same as in readme.md from 1.2.0 (besides preferred port, volume and MONEYBALANCER_JWT_SECRET). 

```yaml
version: "3"
services:
  money-balancer:
    container_name: money-balancer
    image: ghcr.io/dorianim/money-balancer
    ports:
      - 23000:8000
    volumes:
      - /volume1/docker/money-balancer:/data:rw
    environment:
      - MONEYBALANCER_JWT_SECRET=test-test-test-test-test-test-TE
```

Tried latest tag and no tag. MB shows an error after registration either way.
BTW It does create sqlite db each time.

**Comment by dorianim** [comment]
It has to be `JWT_SECRET` (without the prefix) for this version. If you want to use the version on main, you may use the `preview` tag.
